name: "release"

on:
  push:
    branches:
      - "master"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Run Yarn
        run: yarn
      - name: Run Yarn Build
        run: yarn build
      - name: Run Yarn Lint
        run: yarn lint
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Last release"
      - name: Convert repository name to lower case
        run: echo IMAGE_REPOSITORY="$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_ENV"
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            franciscoalamo/woffu-bot
            ghcr.io/${{ github.repository }}
      - name: Publish to Registry
        uses: docker/build-push-action@v3
        with:
          repository: ${{ env.IMAGE_REPOSITORY }}/woffu-bot
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          tag_with_ref: true
          push: true